package com.springbootdemo.model;
// Generated Mar 27, 2023, 9:17:18 AM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employees", schema = "public")
public class Employee implements java.io.Serializable {

    private Long id;
    private Department department;
    private String name;
    private String lastname;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private Set<JobRole> jobRoles = new HashSet<JobRole>(0);

    public Employee() {
    }

    public Employee(Department department, String name, String lastname, Timestamp createdAt, Timestamp updatedAt) {
        this.department = department;
        this.name = name;
        this.lastname = lastname;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Employee(Department department, String name, String lastname, Timestamp createdAt, Timestamp updatedAt,
            Set<JobRole> jobRoles) {
        this.department = department;
        this.name = name;
        this.lastname = lastname;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.jobRoles = jobRoles;
    }

    @GenericGenerator(name = "com.springbootdemo.model.EmployeeIdGenerator", strategy = "org.hibernate.id.IdentityGenerator")
    @Id
    @GeneratedValue(generator = "com.springbootdemo.model.EmployeeIdGenerator")

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id", nullable = false)
    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "lastname", nullable = false)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 35)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "employees_job_roles", schema = "public", joinColumns = {
            @JoinColumn(name = "employee_id", nullable = false, updatable = false) }, inverseJoinColumns = {
                    @JoinColumn(name = "job_role_id", nullable = false, updatable = false) })
    public Set<JobRole> getJobRoles() {
        return this.jobRoles;
    }

    public void setJobRoles(Set<JobRole> jobRoles) {
        this.jobRoles = jobRoles;
    }

}
