package com.springbootdemo.model;
// Generated Mar 31, 2023, 10:43:33 PM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.GenericGenerator;

/**
 * JobRole generated by hbm2java
 */
@Entity
@Table(name = "job_roles", schema = "public")
public class JobRole implements java.io.Serializable {

    private Long id;
    private String name;
    private String description;
    private Set<Employee> employees = new HashSet<Employee>(0);

    public JobRole() {}

    public JobRole(String name) {
        this.name = name;
    }

    public JobRole(String name, String description, Set<Employee> employees) {
        this.name = name;
        this.description = description;
        this.employees = employees;
    }

    @GenericGenerator(
            name = "com.springbootdemo.model.JobRoleIdGenerator",
            strategy = "org.hibernate.id.IdentityGenerator")
    @Id
    @GeneratedValue(generator = "com.springbootdemo.model.JobRoleIdGenerator")
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "employees_job_roles",
            schema = "public",
            joinColumns = {@JoinColumn(name = "job_role_id", nullable = false, updatable = false)},
            inverseJoinColumns = {@JoinColumn(name = "employee_id", nullable = false, updatable = false)})
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }
}
