package com.springbootdemo.model;
// Generated Mar 26, 2023, 12:03:48 AM by Hibernate Tools 6.1.7.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * JobRole generated by hbm2java
 */
@Entity
@Table(name = "job_roles", schema = "public")
public class JobRole implements java.io.Serializable {

    private long id;
    private String name;
    private String description;
    private Set<Employee> employees = new HashSet<Employee>(0);

    public JobRole() {
    }

    public JobRole(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public JobRole(long id, String name, String description, Set<Employee> employees) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.employees = employees;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "employees_job_roles", schema = "public", joinColumns = {
            @JoinColumn(name = "job_role_id", nullable = false, updatable = false) }, inverseJoinColumns = {
                    @JoinColumn(name = "employee_id", nullable = false, updatable = false) })
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

}
